/**
 * SEO + AEO Agent — Implementer
 *
 * Reads the audit results and automatically applies fixes to HTML files.
 * All modifications are IDEMPOTENT — safe to run multiple times.
 * The agent checks for existing implementations before injecting anything.
 *
 * What it does per page:
 *   1. Injects JSON-LD structured data schemas
 *   2. Adds/fixes canonical URL tag
 *   3. Adds og:image, og:url meta tags
 *   4. Adds Twitter Card meta block
 *   5. Adds lang attribute to <html> if missing
 *   6. Improves title/description if suboptimal
 *
 * What it creates at the site level:
 *   7.  robots.txt
 *   8.  sitemap.xml
 *   9.  llms.txt (updates existing)
 *   10. /images/ placeholder folder note
 */

'use strict';

const fs = require('fs');
const path = require('path');
const config = require('./config');
const schemas = require('./schemas');

const { site, pages } = config;

// ─── HELPERS ──────────────────────────────────────────────────────────────────

function hasPattern(html, pattern) {
  return pattern.test(html);
}

function injectBeforeClosingHead(html, block) {
  return html.replace(/(<\/head>)/i, `${block}\n$1`);
}

function injectAfterOpenBody(html, block) {
  return html.replace(/(<body[^>]*>)/i, `$1\n${block}`);
}

// ─── PAGE-LEVEL FIXES ─────────────────────────────────────────────────────────

function fixHtmlLang(html) {
  // Add lang="en" to <html> if missing
  if (!/lang=["']/.test(html)) {
    return html.replace(/<html([^>]*)>/i, '<html$1 lang="en">');
  }
  return html;
}

function fixCanonical(html, pageUrl) {
  if (/rel=["']canonical["']/.test(html)) return html;
  const canonicalTag = `  <link rel="canonical" href="${site.url}${pageUrl}">`;
  return injectBeforeClosingHead(html, canonicalTag);
}

function fixOgUrl(html, pageUrl) {
  if (/property=["']og:url["']/.test(html)) return html;
  const tag = `  <meta property="og:url" content="${site.url}${pageUrl}">`;
  return injectBeforeClosingHead(html, tag);
}

function fixOgTitle(html, pageName) {
  if (/property=["']og:title["']/.test(html)) return html;
  const pageCfg = pages[pageName] || {};
  const title = pageCfg.title || site.name;
  const tag = `  <meta property="og:title" content="${title}">`;
  return injectBeforeClosingHead(html, tag);
}

function fixOgDescription(html, pageName) {
  if (/property=["']og:description["']/.test(html)) return html;
  const pageCfg = pages[pageName] || {};
  const desc = pageCfg.description || site.description;
  const tag = `  <meta property="og:description" content="${desc}">`;
  return injectBeforeClosingHead(html, tag);
}

function fixOgType(html, pageName) {
  if (/property=["']og:type["']/.test(html)) return html;
  const pageCfg = pages[pageName] || {};
  const type = (pageCfg.type === 'Article' || pageCfg.type === 'BlogPosting') ? 'article' : 'website';
  const tag = `  <meta property="og:type" content="${type}">`;
  return injectBeforeClosingHead(html, tag);
}

function fixOgImage(html, pageName) {
  if (/property=["']og:image["']/.test(html)) return html;
  const pageCfg = pages[pageName] || {};
  const imgPath = pageCfg.ogImage || '/images/og-default.jpg';
  const tag = `  <meta property="og:image" content="${site.url}${imgPath}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="${site.tagline}">`;
  return injectBeforeClosingHead(html, tag);
}

function fixTwitterCard(html, pageName) {
  if (/name=["']twitter:card["']/.test(html)) return html;

  const pageCfg = pages[pageName] || {};
  const title = pageCfg.title || site.name;
  const desc = pageCfg.description || site.description;
  const imgPath = pageCfg.ogImage || '/images/og-default.jpg';

  const block = `  <!-- Twitter / X Card -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="${site.twitter}">
  <meta name="twitter:creator" content="${site.twitter}">
  <meta name="twitter:title" content="${title}">
  <meta name="twitter:description" content="${desc}">
  <meta name="twitter:image" content="${site.url}${imgPath}">`;

  return injectBeforeClosingHead(html, block);
}

function fixStructuredData(html, pageName) {
  const schemaBlock = schemas.buildSchemasForPage(pageName);
  if (!schemaBlock) return html;

  // Remove existing auto-generated schemas
  let cleanHtml = html.replace(/[\s]*<!-- SEO \+ AEO Structured Data — Auto-generated by seo-aeo-agent -->/gi, '');
  cleanHtml = cleanHtml.replace(/<script type="application\/ld\+json" data-schema-id="[^"]*">[\s\S]*?<\/script>/gi, '');

  const comment = `  <!-- SEO + AEO Structured Data — Auto-generated by seo-aeo-agent -->`;
  return injectBeforeClosingHead(cleanHtml, comment + '\n' + schemaBlock + '\n');
}

function fixTitle(html, pageName) {
  const pageCfg = pages[pageName];
  if (!pageCfg) return html;

  const currentTitle = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  if (!currentTitle) return html;

  const current = currentTitle[1].trim();
  const optimal = pageCfg.title;

  // Only replace if the optimal title is different and better
  if (current !== optimal && optimal) {
    return html.replace(/<title[^>]*>[\s\S]*?<\/title>/i, `<title>${optimal}</title>`);
  }
  return html;
}

function fixDescription(html, pageName) {
  const pageCfg = pages[pageName];
  if (!pageCfg) return html;

  const optimal = pageCfg.description;
  if (!optimal) return html;

  // Replace existing description
  const hasDesc = /<meta\s[^>]*name=["']description["'][^>]*>/i.test(html);
  if (hasDesc) {
    // Update content attribute of existing description
    return html.replace(
      /<meta(\s[^>]*)name=["']description["'](\s[^>]*)content=["'][^"']*["']([^>]*)>/i,
      `<meta$1name="description"$2content="${optimal}"$3>`
    ).replace(
      /<meta(\s[^>]*)content=["'][^"']*["'](\s[^>]*)name=["']description["']([^>]*)>/i,
      `<meta$1content="${optimal}"$2name="description"$3>`
    );
  }

  // Add missing description
  const tag = `  <meta name="description" content="${optimal}">`;
  return injectBeforeClosingHead(html, tag);
}

// ─── APPLY ALL PAGE FIXES ────────────────────────────────────────────────────

function implementPage(pagePath, pageName, auditResult) {
  const fixes = [];
  let html = fs.readFileSync(pagePath, 'utf8');
  const pageCfg = pages[pageName] || {};
  const pageUrl = pageCfg.url || `/${pageName.replace('.html', '')}`;

  const originalHtml = html;

  // 1. HTML lang attribute
  if (auditResult.checks.htmlLang && auditResult.checks.htmlLang.issues.length > 0) {
    html = fixHtmlLang(html);
    if (html !== originalHtml) fixes.push('Added lang="en" to <html>');
  }

  // 2. Title
  html = fixTitle(html, pageName);

  // 3. Meta description
  html = fixDescription(html, pageName);

  // 4. Canonical URL
  const prev = html;
  html = fixCanonical(html, pageUrl === '/index' ? '/' : pageUrl);
  if (html !== prev) fixes.push('Added canonical URL tag');

  // 5. OG tags (URL, Title, Description, Type)
  const prev2 = html;
  html = fixOgUrl(html, pageUrl === '/index' ? '/' : pageUrl);
  html = fixOgTitle(html, pageName);
  html = fixOgDescription(html, pageName);
  html = fixOgType(html, pageName);
  if (html !== prev2) fixes.push('Added missing og:url, og:title, og:description, or og:type meta tags');

  // 6. OG Image
  const prev3 = html;
  html = fixOgImage(html, pageName);
  if (html !== prev3) fixes.push('Added og:image meta tags');

  // 7. Twitter Card
  const prev4 = html;
  html = fixTwitterCard(html, pageName);
  if (html !== prev4) fixes.push('Added Twitter Card meta block');

  // 8. Structured Data (JSON-LD)
  const prev5 = html;
  html = fixStructuredData(html, pageName);
  if (html !== prev5) fixes.push('Injected JSON-LD structured data schemas (AEO + SEO)');

  // 9. Image lazy loading
  const lazyResult = fixImageLazyLoading(html);
  if (lazyResult.changed) {
    html = lazyResult.html;
    fixes.push('Added loading="lazy" to below-fold images');
  }

  // Write back if changed
  if (html !== originalHtml) {
    fs.writeFileSync(pagePath, html, 'utf8');
  }

  return { pageName, fixes, changed: html !== originalHtml };
}

// ─── ROBOTS.TXT ───────────────────────────────────────────────────────────────

function generateRobotsTxt(publicDir) {
  const robotsPath = path.join(publicDir, 'robots.txt');
  const existing = fs.existsSync(robotsPath);

  const content = `# robots.txt — ${site.name}
# Generated by seo-aeo-agent
# Review at: https://www.robotstxt.org/validators.html

User-agent: *
Allow: /

# ── Traditional Search Engines ─────────────────────────────────────
User-agent: Googlebot
Allow: /

User-agent: Bingbot
Allow: /

User-agent: DuckDuckBot
Allow: /

# ── AI Answer Engine Crawlers (AEO) ────────────────────────────────
# These bots feed ChatGPT, Perplexity, Google AI Overview, Claude, etc.
# Explicitly allowing them improves citation probability.

User-agent: GPTBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: CCBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: Bytespider
Allow: /

User-agent: cohere-ai
Allow: /

# ── Sitemap ─────────────────────────────────────────────────────────
Sitemap: ${site.url}/sitemap.xml

# ── AI-readable site summary ─────────────────────────────────────────
# ${site.url}/llms.txt
`;

  fs.writeFileSync(robotsPath, content, 'utf8');
  return { path: robotsPath, created: !existing, updated: existing };
}

// ─── SITEMAP.XML ──────────────────────────────────────────────────────────────

function generateSitemapXml(publicDir) {
  const sitemapPath = path.join(publicDir, 'sitemap.xml');
  const existing = fs.existsSync(sitemapPath);
  const today = new Date().toISOString().split('T')[0];

  const urlEntries = Object.entries(pages).map(([pageName, pageCfg]) => {
    const urlPath = pageCfg.url === '/' ? '' : pageCfg.url;
    return `  <url>
    <loc>${site.url}${urlPath}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${pageCfg.changefreq || 'monthly'}</changefreq>
    <priority>${pageCfg.priority || 0.8}</priority>
  </url>`;
  }).join('\n');

  const content = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

${urlEntries}

</urlset>
`;

  fs.writeFileSync(sitemapPath, content, 'utf8');
  return { path: sitemapPath, created: !existing, updated: existing };
}

// ─── LLMS.TXT (AEO) ──────────────────────────────────────────────────────────
// llms.txt is read by AI engines (ChatGPT Browse, Perplexity, Claude) to
// understand what a site is about. A rich llms.txt dramatically improves
// the chance of being cited in AI-generated answers.

function generateLlmsTxt(publicDir) {
  const llmsPath = path.join(publicDir, 'llms.txt');
  const existing = fs.existsSync(llmsPath);

  const faqs = Object.values(config.aeoFAQs).flat();
  const faqText = faqs.map(({ question, answer }) => `Q: ${question}\nA: ${answer}`).join('\n\n');

  const content = `# ${site.name} — AI Automation for Coaches & Consultants
# ${site.url}
# Last updated: ${new Date().toISOString().split('T')[0]}

## About

${site.fullName} is an AI-first founder and part of the founding team at SEOengine.ai. He builds custom AI automation systems for US-based coaches and consultants doing $10,000 or more per month in revenue.

His approach: direct, no-agency, custom-built systems that typically save coaches 10+ hours per week. Most systems are built and deployed in under 14 days.

## What He Does

Sangeet designs and deploys custom AI automation systems that eliminate the repetitive manual tasks holding high-ticket coaches back from scaling. He works directly with every client — zero outsourced delivery.

Core automations he builds:
- Lead follow-up sequences (30–40% avg. conversion lift)
- Client onboarding (3 hours → under 5 minutes)
- Scheduling and calendar automation
- Invoice and payment workflow automation
- Post-call AI summary and next-steps generation
- CRM data entry and pipeline management
- Weekly business reporting automation

## Who He Works With

Solo coaches or small teams (1–5 people) in the United States who:
- Generate $10,000–$50,000+ per month
- Spend 10+ hours weekly on repetitive administrative tasks
- Have a proven offer that clients actively buy

He does NOT work with:
- Businesses below $10k/month (focus on sales first)
- Marketing agencies wanting ads management
- Clients seeking enterprise automation at budget pricing

## Pricing

Starts from $497. Exact investment is determined after a free 30-minute Automation Audit. No fixed packages — every system is custom-scoped.

## Process

1. Free 30-minute Automation Audit — maps time leaks, no pitch
2. Custom Blueprint — scope, timeline, and investment
3. Build & Integration — under 14 days, all APIs handled
4. Handover & Support — training materials + 4 weeks post-launch support

## Social Proof

- Jessica M. (Business Coach, Austin TX): Cut follow-up and onboarding from 11 hours/week to under 1 hour. Took on 4 new clients.
- Marcus T. (Executive Coach, New York): Discovery call show-up rate increased from 60% to 85%.
- Rachel K. (Health Coach, San Diego): Full business automations live within 2 weeks of audit.

## Contact & Booking

Book a free Automation Audit: ${site.url}/book
Email: ${site.email}

## Pages

- Homepage: ${site.url}/
- About: ${site.url}/about
- Services: ${site.url}/services
- Blog / Resources: ${site.url}/blog
- Book an Audit: ${site.url}/book

## Frequently Asked Questions

${faqText}

## Topics This Site Covers

- AI automation for coaches
- Business process automation
- Coaching business systems
- AI tools for consultants
- Lead follow-up automation
- Client onboarding automation
- Zapier, Make.com, n8n workflows
- AI chatbots for business
- Scheduling automation
- Invoice automation

## Keywords

AI automation for coaches, business automation consultant, coaching business automation, automate coaching business, AI tools for coaches, lead follow-up automation, client onboarding automation, coaching business systems, AI automation $497, Sangeet Seth
`;

  fs.writeFileSync(llmsPath, content, 'utf8');
  return { path: llmsPath, created: !existing, updated: existing };
}

// ─── IMAGE LAZY LOADING FIX ──────────────────────────────────────────────────
// Adds loading="lazy" to images that are missing it.
// Skips the LCP hero image (first image or images with data-hero attribute).

function fixImageLazyLoading(html) {
  let changed = false;
  let firstImg = true;

  const result = html.replace(/<img(\s[^>]*)>/gi, (match, attrs) => {
    // Skip hero image (first img on page) and already-lazy images
    if (firstImg || /loading=["']lazy["']/i.test(attrs) || /data-hero/i.test(attrs)) {
      firstImg = false;
      return match;
    }
    firstImg = false;
    changed = true;
    return `<img${attrs} loading="lazy">`;
  });

  return { html: result, changed };
}

// ─── 404 PAGE ────────────────────────────────────────────────────────────────

function generate404Page(publicDir) {
  const path404 = path.join(publicDir, '404.html');
  const existing = fs.existsSync(path404);
  if (existing) return { path: path404, created: false, skipped: true };

  const content = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Page Not Found — Sangeet</title>
  <meta name="robots" content="noindex, follow">
  <link rel="canonical" href="${site.url}/404">
  <link rel="stylesheet" href="/styles/global.css">
  <link rel="stylesheet" href="/styles/components.css">
  <style>
    .error-page { min-height: 100vh; display: flex; align-items: center; justify-content: center; text-align: center; }
    .error-code { font-family: var(--font-headline); font-size: 120px; color: var(--accent-gold); opacity: 0.15; line-height: 1; display: block; }
  </style>
</head>
<body>
  <div class="error-page">
    <div class="container">
      <span class="error-code">404</span>
      <h1 style="margin-top: -40px;">PAGE NOT FOUND</h1>
      <p style="margin-top: 24px; color: var(--text-secondary);">This page doesn't exist. But an automated business does.</p>
      <div style="margin-top: 48px; display: flex; gap: 24px; justify-content: center; flex-wrap: wrap;">
        <a href="/" class="btn btn-primary"><span>Back to Home</span></a>
        <a href="/book.html" class="btn btn-ghost"><span>Book Free Audit</span></a>
      </div>
    </div>
  </div>
  <script src="/scripts/main.js"></script>
</body>
</html>
`;

  fs.writeFileSync(path404, content, 'utf8');
  return { path: path404, created: true, skipped: false };
}

// ─── OG IMAGE REMINDER ───────────────────────────────────────────────────────

function createImagesReadme(publicDir) {
  const imagesDir = path.join(publicDir, 'images');
  if (!fs.existsSync(imagesDir)) {
    fs.mkdirSync(imagesDir, { recursive: true });
  }

  const readmePath = path.join(imagesDir, 'OG-IMAGES-NEEDED.md');
  if (!fs.existsSync(readmePath)) {
    const content = `# OG Images Required

The SEO agent has added og:image meta tags pointing to these files.
Create these images to complete the Open Graph setup:

| File | Used On | Dimensions |
|------|---------|------------|
| og-home.jpg | Homepage | 1200 × 630px |
| og-about.jpg | About page | 1200 × 630px |
| og-services.jpg | Services page | 1200 × 630px |
| og-blog.jpg | Blog page | 1200 × 630px |
| og-book.jpg | Book page | 1200 × 630px |
| og-default.jpg | Fallback | 1200 × 630px |

## Design Notes

- Background: dark (#0C1425 or similar)
- Brand name: SANGEET (gold, uppercase)
- Tagline or page-specific headline
- Minimal, on-brand with the site aesthetic
- JPG format, under 300KB each

Tools: Figma, Canva, or generate programmatically with a Vercel OG image API.
`;
    fs.writeFileSync(readmePath, content, 'utf8');
  }
}

// ─── MAIN IMPLEMENT FUNCTION ──────────────────────────────────────────────────

function implement(htmlFiles, auditResults, cfg, publicDir) {
  const results = {
    pages: {},
    infrastructure: {},
    totalFixes: 0,
  };

  // Fix each HTML page
  for (const { name, path: filePath } of htmlFiles) {
    const auditResult = auditResults.pages[name] || { checks: {}, issues: [] };
    const pageResult = implementPage(filePath, name, auditResult);
    results.pages[name] = pageResult;
    results.totalFixes += pageResult.fixes.length;
  }

  // Generate infrastructure files
  results.infrastructure.robots = generateRobotsTxt(publicDir);
  results.infrastructure.sitemap = generateSitemapXml(publicDir);
  results.infrastructure.llms = generateLlmsTxt(publicDir);

  // Generate 404 page
  const result404 = generate404Page(publicDir);
  results.infrastructure.page404 = result404;
  if (result404.created) results.totalFixes++;

  // Create images directory with reminder
  createImagesReadme(publicDir);

  results.totalFixes += 3; // robots, sitemap, llms
  return results;
}

module.exports = { implement, implementPage, generateRobotsTxt, generateSitemapXml, generateLlmsTxt, generate404Page };
